"""empty message

Revision ID: 4e0be19a341f
Revises: 5f95488fdaa3
Create Date: 2018-01-11 10:12:03.562626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e0be19a341f'
down_revision = '5f95488fdaa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_first_name'), 'User', ['first_name'], unique=False)
    op.create_index(op.f('ix_User_last_name'), 'User', ['last_name'], unique=False)
    op.create_index(op.f('ix_User_username'), 'User', ['username'], unique=True)
    op.drop_index('ix_User_email', table_name='User')
    op.drop_index('ix_User_first_name', table_name='User')
    op.drop_index('ix_User_last_name', table_name='User')
    op.drop_index('ix_User_username', table_name='User')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_User_username', 'User', ['username'], unique=True)
    op.create_index('ix_User_last_name', 'User', ['last_name'], unique=False)
    op.create_index('ix_User_first_name', 'User', ['first_name'], unique=False)
    op.create_index('ix_User_email', 'User', ['email'], unique=True)
    op.drop_index(op.f('ix_User_username'), table_name='User')
    op.drop_index(op.f('ix_User_last_name'), table_name='User')
    op.drop_index(op.f('ix_User_first_name'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    # ### end Alembic commands ###
