"""empty message

Revision ID: 96057603ec41
Revises: 847a90ffdffb
Create Date: 2018-01-12 09:45:47.773893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96057603ec41'
down_revision = '847a90ffdffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_first_name'), 'User', ['first_name'], unique=False)
    op.create_index(op.f('ix_User_last_name'), 'User', ['last_name'], unique=False)
    op.create_index(op.f('ix_User_username'), 'User', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_username'), table_name='User')
    op.drop_index(op.f('ix_User_last_name'), table_name='User')
    op.drop_index(op.f('ix_User_first_name'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    # ### end Alembic commands ###
